name: BCC Build and tests

on: push

jobs:
  cross_builds:
    runs-on: ubuntu-18.04 # FIXME add this to the matrix
    strategy:
      matrix:
        env:
        - TYPE: Debug
        - TYPE: Release
    steps:
    - uses: actions/checkout@v2
    - name: Build docker container
      run: |
        docker build -t bcc-docker -f docker/Dockerfile.tests .
    - name: Run bcc build
      env: ${{ matrix.env }}
      run: |
        docker run --privileged -v ${PWD}:${PWD} -v /sys/kernel/debug:/sys/kernel/debug:rw -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -e RUN_TESTS=1 bcc-docker ${PWD}/build-${TYPE} ${TYPE} -j9
